### ISSUE TITLE
Fix problème avec les polices et ajouter de nouvelles fonctionalités (prompt & profils enregistrés) 

### ISSUE THREAD

**Issue by Apoptoz** [tdopierre/AttesationNumeriqueCOVID-19#1]
Salut,

Merci pour ton programme, c'est super utile et tu as été très rapide.

J'ai eu un souci avec la police : Arial n'était pas installé chez moi, je l'ai installé et il est trouvable plutot en tant que `arial.ttf`, et ImageFont est case sensitive. J'ai ajouté quelques exceptions donc.

Je me suis dit ensuite que comme c'était toujours les mêmes infos que l'on remplit, de les enregistrer localement pour être réutilisable, puis un petit prompt pour remplir plus agréablement les infos restantes. J'ai changé donc un peu ton script pour mettre des fonctions que j'appelle facilement à partir de mon autre fichier python.

Le fork est disponible ici :
https://github.com/Apoptoz/AttestationNumeriqueCOVID-19

J'ai encore quelques idées : 
- Un argument pour register_info.py pour sélectionner direct un profil
`python register_info.py Roger`
- Un argument pour changer le nom du fichier d'output (ou bien par défaut `JJ-MM-HH-MM-ProfilName.pdf` ?)

Un portage web serait définitivement utile pour les non-initiés et pour l'utilisation smartphone aussi...

Je te laisse décider si mon fork t'intéresse ou pas.

Merci encore !

**Comment by zeysh** [comment]
Hello,

J'avais le même soucis:

```bash
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    cross = get_cross()
  File "main.py", line 80, in get_cross
    image_font = ImageFont.truetype("Arial.ttf", 35)
  File "/home/user/src/python/covid19/lib/python3.7/site-packages/PIL/ImageFont.py", line 648, in truetype
    return freetype(font)
  File "/home/user/src/python/covid19/lib/python3.7/site-packages/PIL/ImageFont.py", line 645, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/user/src/python/covid19/lib/python3.7/site-packages/PIL/ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
```

L'installation du paquet "ttf-mscorefonts-installer" (sous Ubuntu) a réglé le problème.
Merci
